# Generated by Django 5.1 on 2024-08-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authors_last_login_authors_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='last_login',
        ),
    ]
