# Generated by Django 5.1 on 2024-08-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_authors_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='password',
        ),
    ]
