# Generated by Django 5.1 on 2024-08-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_authors_delete_acceptus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
